version: '3.4'

services:
  servicea:
    container_name: serviceA
    build:
      context: ./ServiceA
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - SERVICEB_URL=http://serviceb:8080
    depends_on:
      - serviceb

  serviceb:
    container_name: serviceB
    build:
      context: ./ServiceB
      dockerfile: Dockerfile
    ports:
      - "5002:8080"